// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListAPI.Data;

#nullable disable

namespace ShoppingListAPI.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251225213425_add-ForeginKey")]
    partial class addForeginKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingListAPI.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.ProductInLIst", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShopListKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShopListKey");

                    b.ToTable("ProductIns");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.ShopList", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserOKey")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.HasIndex("UserOKey");

                    b.ToTable("ShopLists");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.UserO", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("UserOs");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.ProductInLIst", b =>
                {
                    b.HasOne("ShoppingListAPI.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoppingListAPI.Core.Models.ShopList", null)
                        .WithMany("ListProductsInLIst")
                        .HasForeignKey("ShopListKey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.ShopList", b =>
                {
                    b.HasOne("ShoppingListAPI.Core.Models.UserO", "UserO")
                        .WithMany("ShopLists")
                        .HasForeignKey("UserOKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserO");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.ShopList", b =>
                {
                    b.Navigation("ListProductsInLIst");
                });

            modelBuilder.Entity("ShoppingListAPI.Core.Models.UserO", b =>
                {
                    b.Navigation("ShopLists");
                });
#pragma warning restore 612, 618
        }
    }
}
